server:
  port: 9000
spring:
  application:
    name: serviceEquipment
  profiles:
    active:
    - dev
  cloud:
    config:
      uri:
      - http://localhost:8888/
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true